### ISSUE TITLE
Detailed Menu Item Persists

### ISSUE THREAD

**Issue by brandonnhem** [CECS-445-Project/ServerMatch#36]
**How to Replicate:**

1. Open Menu
2. Long press on Menu Item
3. With detailed Menu Item open, press the hamburger menu
4. Select any Navigation Drawer option

**Expected Results:**

When switching to a different fragment, the detailed menu should disappear. 

I have noticed that a press/swipe back with system navigation solves the problem.

**Comment by JCPasillas** [comment]
This is fixed by adding a background to the fragments. I did this in my logoutDialog branch, so this should be fixed when we merge it.

**Comment by brandonnhem** [comment]
Should I close the issue then?

**Comment by JCPasillas** [comment]
Not until we finally do the merge to master so we know its fixed officially.
